config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :matches, only: [:index, :show, :new, :create] do
    resources :match_users, only: [:create]
  end

  resources :user, only: [:show] do
    resource :profile, only: [:show]
  end
  resources :clubs, only: [:index, :show, :new, :create] do
    resources :club_requests, only: [:create]
  end

  resources :club_requests, only: [:update]


  resources :challenges, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :creators do
    resources :tournaments
  end

  resources :tournaments, only: [:show, :index] do
    resources :tournament_requests, only: [:create]
    resources :tournament_groups, only: [:show, :create, :index]
    resources :tournament_knockouts, only: [:show, :create, :index]
  end

  resources :tournament_group, only: [:show] do
    resources :tournament_matches, only: [:show, :create, :index]
  end

  resources :tournament_knockout, only: [:show] do
    resources :tournament_matches, only: [:show]
  end

  resources :home_teams, only: [:show]
  resources :away_teams, only: [:show]
  resources :tournament_matches, only: [:update]
  resources :tournament_requests, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tournament_match.rb
class TournamentMatch < ApplicationRecord
  belongs_to :tournament_group, optional: true
  belongs_to :tournament
  belongs_to :tournament_knockout, optional: true
  belongs_to :home_team
  belongs_to :away_team
  has_many :club_tournament_matches

end

app/controllers/tournament_matches_controller.rb
class TournamentMatchesController < ApplicationController

  def show
    @tournament_match = TournamentMatch.find(params[:id])
    @home_team = @tournament_match.home_team
    @away_team = @tournament_match.away_team
    authorize @tournament_match
  end


  #When adjusting to make the code fit different tournamnet sizes, use a case @tournament that take while @tournament.amount_of_teams
  def update
    @tournament_match = TournamentMatch.find(params[:id])
    @home_team = @tournament_match.home_team
    @away_team = @tournament_match.away_team
    @tournament = @tournament_match.tournament

    #method for adding points to group table after the referee press "finished"
    if @home_team.goals > @away_team.goals
      @home_team.tournament_club.update!(points: @home_team.tournament_club.points += 3)
      @tournament_match.update!(status: "finished")
    elsif @home_team.goals < @away_team.goals
      @away_team.tournament_club.update!(points: @away_team.tournament_club.points += 3)
      @tournament_match.update!(status: "finished")
    else
      @away_team.tournament_club.update!(points: @away_team.tournament_club.points += 1)
      @home_team.tournament_club.update!(points: @home_team.tournament_club.points += 1)
      @tournament_match.update!(status: "finished")
    end

    #adding a winner to knockout matches when the referee press "finished"
    if @tournament_match.tournament_knockout.present?
      if @home_team.goals > @away_team.goals
        @tournament_match.update!(winner: @home_team.tournament_club.id)
        @tournament_match.update!(status: "finished")
      else
        @tournament_match.update!(winner: @away_team.tournament_club.id)
        @tournament_match.update!(status: "finished")
      end

      #creating a new stage of the tournament knockouts after the winners has been set above
      #the unless statements checks that the match is indeed a "semi-final" and then it checks that there are no more matches "ongoing" so as to know its the last one and then it checks that the match is not a final
      if @tournament.tournament_knockouts.where(stage: "Semi-final").present? && @tournament.tournament_matches.where(status: "ongoing").present? == false && @tournament_match.tournament_knockout.stage != "Final"
        #it creates a new tournamentknockout where the stage is a Final
        @tournament_knockout = TournamentKnockout.create!(tournament: @tournament, stage: "Final")
        #adds the winners of the semifinal through look at index
        @home_team = HomeTeam.create!(tournament_club: TournamentClub.find(@tournament_match.winner), goals: 0)
        @away_team = AwayTeam.create!(tournament_club: TournamentClub.find(@tournament.tournament_matches[-2].winner), goals: 0)
        @tournament_match = TournamentMatch.create!(tournament_knockout: @tournament_knockout, tournament: @tournament, home_team: @home_team, away_team: @away_team)
      end
      redirect_to tournament_tournament_knockouts_path(@tournament, @tournament.tournament_knockouts)
    end
    #if the tournament match is a final
    if @tournament.tournament_knockouts.where(stage: "Final").present?
      @tournament.update!(tournament_winner: @tournament_match.winner)
    end
    #METHOD FOR CREATING TOURNAMENTKNOCKOUTS after tournament groups
    if TournamentMatch.where(status: "ongoing").present? == false && @tournament_match.tournament_group.present?
      case @tournament.amount_of_teams
      when 8
        #finds the groups with the clubs in the standings order
        @tournament_clubs1 = TournamentClub.where(tournament_group: @tournament.tournament_groups.first).order(points: :desc)
        @tournament_clubs2 = TournamentClub.where(tournament_group: @tournament.tournament_groups.last).order(points: :desc)
        n = 0
        c = 1
        2.times.map do
          @tournament_knockout = TournamentKnockout.create!(tournament: @tournament, stage: "Semi-final")
          #takes the winner from group 1 and pairs it with second place from group two
          @home_team = HomeTeam.create!(tournament_club: @tournament_clubs1[n], goals: 0)
          @away_team = AwayTeam.create!(tournament_club: @tournament_clubs2[c], goals: 0)
          #creates a tournament knockout with theese teams
          @tournament_match = TournamentMatch.create!(tournament_knockout: @tournament_knockout, tournament: @tournament, home_team: @home_team, away_team: @away_team)
          #then ads index +1 to the first group to find the second place and then takes index -1 to the second group to find the first place
          n += 1
          c -= 1
        end
          redirect_to tournament_path(@tournament)

      when 16
        @tournament_clubs1 = TournamentClub.where(tournament_group: @tournament.tournament_groups.first).order(points: :desc)
        @tournament_clubs2 = TournamentClub.where(tournament_group: @tournament.tournament_groups[1]).order(points: :desc)
        @tournament_clubs3 = TournamentClub.where(tournament_group: @tournament.tournament_groups[2]).order(points: :desc)
        @tournament_clubs4 = TournamentClub.where(tournament_group: @tournament.tournament_groups.last).order(points: :desc)


          @tournament_knockout = TournamentKnockout.create!(tournament: @tournament, stage: "Semi-final")
          #takes the winner from group 1 and pairs it with second place from group two
          @home_team = HomeTeam.create!(tournament_club: @tournament_clubs1[0], goals: 0)
          @away_team = AwayTeam.create!(tournament_club: @tournament_clubs4[0], goals: 0)
          #creates a tournament knockout with theese teams
          @tournament_match = TournamentMatch.create!(tournament_knockout: @tournament_knockout, tournament: @tournament, home_team: @home_team, away_team: @away_team)

          @tournament_knockout = TournamentKnockout.create!(tournament: @tournament, stage: "Semi-final")

          @home_team = HomeTeam.create!(tournament_club: @tournament_clubs2[0], goals: 0)
          @away_team = AwayTeam.create!(tournament_club: @tournament_clubs3[0], goals: 0)
          #creates a tournament knockout with theese teams
          @tournament_match = TournamentMatch.create!(tournament_knockout: @tournament_knockout, tournament: @tournament, home_team: @home_team, away_team: @away_team)

          #then ads index +1 to the first group to find the second place and then takes index -1 to the second group to find the first place
          redirect_to tournament_path(@tournament)
      else

      end
    end
    if @tournament_match.tournament_group.present?
      redirect_to tournament_tournament_group_path(@tournament, @tournament_match.tournament_group)
    end
    @tournament_match.save!
    authorize @tournament_match
  end

end

app/views/tournament_matches/show.html.erb
<%#= link_to 'goal!', tournament_match_path(team_1.id, team_1_score: += 1),class:"button-wb", method: :patch do %>
<div class="container">
  <div class="match-card">
    <div class="row" style="display: flex; justify-content: space-evenly; text-align: center; padding-top: 16px; margin-bottom: 8px;">
      <div class="x" style="width: 30%">
        <% if @home_team.tournament_club.club.photo.attached? %>
          <%= cl_image_tag @home_team.tournament_club.club.photo.key, class:"w-75 ml-4" %>
        <% else %>
          <%= image_tag "footballpitch.jpg", class:"profile-img-club-show", alt:"Klubb logga" %>
        <% end %>
      </div>
      <div class="x" style="width: 30%; margin-top: auto;">
        <h1 style="color: yellow;">versus</h1>
      </div>
      <div class="x" style="width: 30%">
        <% if @away_team.tournament_club.club.photo.attached? %>
          <%= cl_image_tag @away_team.tournament_club.club.photo.key, class:"w-75 mr-4", alt:"Klubb logga" %>
        <% else %>
          <%= image_tag "footballpitch.jpg", class:"profile-img-club-show", alt:"Klubb logga" %>
        <% end %>
      </div>
    </div>
    <div class="row" style="justify-content: center; text-align: center;" >
      <div class="x" style="width: 30%;">
        <h3 class="text-white mt-2"><%= "#{@home_team.tournament_club.club.name}" %></h3>
      </div>
      <div class="x" style="width: 30%;">
        <h3 class="text-white mt-2"><%= "#{@home_team.goals} : #{@away_team.goals}" %> </h3>
      </div>
      <div class="x" style="width: 30%;">
        <h3 class="text-white mt-2"><%= "#{@away_team.tournament_club.club.name}" %></h3>
      </div>
    </div>
  </div>
</div>
<div class="row mt-3" style="justify-content: center;">
  <div class="d-flex">
    <div class="button-ref mr-1">
     <%= link_to "#{@home_team.tournament_club.club.name.upcase} GOAL!", home_team_path(@home_team), method: :patch %>
    </div>
    <div class="button-ref ml-1" style="justify-content: center;">
      <%= link_to "#{@away_team.tournament_club.club.name.upcase} GOAL!", away_team_path(@away_team), method: :patch %>
    </div>
  </div>
</div>
<% if current_user == @tournament_match.tournament.creator.user %>
  <div class="button-ref-f">
    <%= link_to "Full time", tournament_match_path(@tournament_match), method: :patch %>
  </div>
<% end %>
<div class="row" style="justify-content: center;">
  <%= link_to "Tillbaks", tournament_tournament_groups_path(@tournament_match.tournament, @tournament_match.tournament.tournament_groups), class:"button-wb" %>
</div>