config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :matches, only: [:index, :show, :new, :create] do
    resources :match_users, only: [:create]
  end

  resources :user, only: [:show] do
    resource :profile, only: [:show]
  end
  resources :clubs, only: [:index, :show, :new, :create] do
    resources :club_requests, only: [:create]
  end

  resources :club_requests, only: [:update]


  resources :challenges, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :creators do
    resources :tournaments
  end

  resources :tournaments, only: [:show, :index] do
    resources :tournament_requests, only: [:create]
    resources :tournament_groups, only: [:show, :create, :index]
    resources :tournament_knockouts, only: [:show, :create, :index]
  end

  resources :tournament_group, only: [:show] do
    resources :tournament_matches, only: [:show, :create, :index]
  end

  resources :tournament_knockout, only: [:show] do
    resources :tournament_matches, only: [:show]
  end

  resources :home_teams, only: [:show]
  resources :away_teams, only: [:show]
  resources :tournament_matches, only: [:update]
  resources :tournament_requests, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tournament_group.rb
class TournamentGroup < ApplicationRecord
  belongs_to :tournament
  has_many :tournament_matches
  has_many :tournament_clubs

  def standings
    @tournament_clubs ||= TournamentClub.where(tournament_group: self).order(points: :desc)
  end

  def first_place
    standings[0]
  end

  def second_place
    standings[1]
  end

  def knocked_out
    standings[2..-1]
  end
end

app/controllers/tournament_groups_controller.rb
class TournamentGroupsController < ApplicationController
  before_action :set_tournament, only: [:index]
  def show
    @tournament_group = TournamentGroup.find(params[:id])
    authorize @tournament_group
  end

  def index
    @tournament_groups = policy_scope(@tournament.tournament_groups)
  end

  #create a update method that creates tournament knockouts if all group matches status are set to "finished"
  #change the schema so that tournament_clubs has reference to tournament_knockout with null: true
  private

  def set_tournament
    @tournament = Tournament.find(params[:tournament_id])
  end

end

app/views/tournament_groups/index.html.erb
  <div class="my-2 text-center">
    <h1>Tournament Groups</h1>
  </div>
<div class="container">
  <div class="row justify-content-center">
    <% @tournament_groups.each_with_index do |group, index| %>
      <div class="creator-card">
        <%= link_to tournament_tournament_group_path(@tournament, group), class: "d-block" do %>
          <h2 class="x" style="color: yellow;"><%= "Group - #{index + 1}" %></h2>
          <% group.standings.each_with_index do |team, index| %>
            <div class="row solid" style=" margin-left: auto; margin-right: auto; ">
              <h2 class="text_yellow" style="margin-top: 13px; color: yellow;"><%= index +1 %>.</h2>
              <h2 class="x" style="color: yellow;"><%= cl_image_tag team.club.photo.key%> <%= team.club.name %></h2>
              <h2 class="text-white" style="margin-top: 13px; margin-left: 30px;"><%= "#{team.points}p" %></h2>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row" style="justify-content: center;">
  <%= link_to "Tillbaks", tournament_path(@tournament_groups[0].tournament), class:"button-wb" %>
</div>

app/views/tournament_groups/show.html.erb
<div class="container">
  <div class="row" style="justify-content: center;">

  </div>
  <div class="row" style="justify-content: center;">
    <div class="participating-teams">
      <h2>Nästa matcher</h2>
    </div>
  </div>
  <% @tournament_group.tournament_matches.shuffle.each do |match| %>
    <div class="row" style="justify-content: center;">
      <% if match.status == "ongoing" %>
        <%= link_to tournament_group_tournament_match_path( @tournament_group, match), class: "w-100" do  %>
          <div class="match-card py-3">
            <% if match.home_team.tournament_club.club.photo.attached? %>
              <h2><%= cl_image_tag match.home_team.tournament_club.club.photo.key, class:"w-25 mr-3", alt:"Klubb logga" %> vs <%= cl_image_tag match.away_team.tournament_club.club.photo.key, class:"w-25 ml-3", alt:"Klubb logga" %></h2>
            <% else %>
              <%= image_tag "footballpitch.jpg", class:"profile-img-club", alt:"Klubb logga" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="row" style="justify-content: center;">
    <div class="participating-teams">
      <h2>Avgjorda matcher</h2>
    </div>
  </div>
  <% @tournament_group.tournament_matches.each do |match| %>
    <div class="row" style="justify-content: center;">
      <% if match.status == "finished" %>
        <%= link_to tournament_group_tournament_match_path( @tournament_group, match), class: "w-100" do  %>
          <div class="match-card py-3">
            <% if match.home_team.tournament_club.club.photo.attached? %>
              <h2><%= cl_image_tag match.home_team.tournament_club.club.photo.key, class:"w-25 mr-3", alt:"Klubb logga" %> vs <%= cl_image_tag match.away_team.tournament_club.club.photo.key, class:"w-25 ml-3", alt:"Klubb logga" %></h2>
              <p><%= match.home_team.goals %> || <%= match.away_team.goals %></p>
            <% else %>
              <%= image_tag "footballpitch.jpg", class:"profile-img-club", alt:"Klubb logga" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="row" style="justify-content: center;">
  <%= link_to "Tillbaks", tournament_tournament_groups_path(@tournament_group.tournament, @tournament_group.tournament.tournament_groups), class:"button-wb" %>
</div>
    <%# <div class="creator-card">
      <% @tournament_group.standings.each_with_index do |team, index| %>
        <%# <div class="row" style="justify-content: space-between; margin-left: auto; margin-right: auto; text-decoration: underline;"> %>
          <%# <h2><%= index +1 %></h2>
          <%# <h2><%= team.club.name %></h2>
          <%# <h2 class="text-white"><%= "#{team.points}p" %></h2>
        <%# </div> %>
      <%# <% end %>
    <%# </div> %>