config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :matches, only: [:index, :show, :new, :create] do
    resources :match_users, only: [:create]
  end

  resources :user, only: [:show] do
    resource :profile, only: [:show]
  end
  resources :clubs, only: [:index, :show, :new, :create] do
    resources :club_requests, only: [:create]
  end

  resources :club_requests, only: [:update]


  resources :challenges, only: [] do
    member do
      patch :accept
      patch :decline
    end
  end

  resources :creators do
    resources :tournaments
  end

  resources :tournaments, only: [:show, :index] do
    resources :tournament_requests, only: [:create]
    resources :tournament_groups, only: [:show, :create, :index]
    resources :tournament_knockouts, only: [:show, :create, :index]
  end

  resources :tournament_group, only: [:show] do
    resources :tournament_matches, only: [:show, :create, :index]
  end

  resources :tournament_knockout, only: [:show] do
    resources :tournament_matches, only: [:show]
  end

  resources :home_teams, only: [:show]
  resources :away_teams, only: [:show]
  resources :tournament_matches, only: [:update]
  resources :tournament_requests, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :creator
  has_many :tournament_groups
  has_many :tournament_knockouts
  has_many :tournament_matches
  has_many :tournament_requests
  has_many :clubs, through: :tournament_requests

  validates :start_at, :name, :description, :rules, :age_group, :skill_level, :amount_of_teams, presence: true

  after_create :create_tournament_groups

  def teams
    Club.joins(:tournament_requests).where(tournament_requests: { status: "accepted", tournament: self })
  end

  def pending_tournament_request
    Club.joins(:tournament_requests).where(tournament_requests: { status: "pending" })
  end


  def number_of_groups
    number_of_groups = amount_of_teams / 4
  end

  private

  def create_tournament_groups
    number_of_groups.times do
      TournamentGroup.create!(tournament: self)
    end
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
    before_action :set_tournament, only: [:show]

  def new
    @creator = Creator.find(params[:creator_id])
    @tournament = Tournament.new
    authorize @tournament
  end

  def index
    @tournaments = policy_scope(Tournament.all)
  end

  def creator_tournaments
    @creator = Creator.find(params[:creator_id])
    @creator_tournaments = policy_scope(Creator.tournaments)
  end

  def create
    @tournament = Tournament.new(strong_params)
    @creator = Creator.find(params[:creator_id])
    @tournament.creator = @creator
    if @tournament.save
      redirect_to [@creator, @tournament]
     else
       render :new
    end
     authorize @tournament
  end

  def show
    @existing_request_from_club = @tournament.pending_tournament_request
    @pending_tournament_requests = @tournament.tournament_requests.pending
    if @tournament.tournament_winner > 0
      @tournament_winner = TournamentClub.find(@tournament.tournament_winner)
    end
    authorize @tournament
  end

  private

  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def strong_params
    params.require(:tournament).permit(:name, :description, :start_at, :rules, :age_group, :skill_level)
  end
end

app/views/tournaments/index.html.erb
<div class="my-2 text-center">
  <h1>All upcoming Tournaments:</h1>
</div>
<div class="container">
  <% @tournaments.each do |tournament| %>
    <div class="row" style="justify-content: center;">
      <div class="col-10">
        <%= link_to creator_tournament_path(tournament.creator, tournament), class: "d-block" do %>
          <div class="container-profile w-100">
            <div class="content-profile-club p-0">
                <div class="sub-content">
                    <%= image_tag 'kickofftrophy.png', class:"w-100" %>
                    <h1><%= tournament.name %></h1>
                    <p><strong>Description: </strong> <%= tournament.description %></p>
                  <div class="tournament-card-content">
                    <p><i class="fas fa-fist-raised"></i> <%= tournament.skill_level %></i></p>
                    <p><i class="far fa-id-badge"></i></i> <%= tournament.age_group %></i></p>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tournaments/show.html.erb
 <div class="banner-tournament">
  <div class="row" style="justify-content: center; text-align: center;">
    <%= image_tag "supercenter.png"%>
      <div id="text">
        <h1><%= @tournament.name %></h1>
        <p><%= @tournament.creator.name %></p>
      </div>
  </div>
</div>

<div class="container" style="padding-left: 25px; padding-right: 25px;">
  <div class="row mt-3" style="text-align: center; justify-content: center;">
    <div class="description">
      <h2>Info om -> <%= @tournament.name %></h2>
      <p><%= @tournament.description %></p>
    </div>
  </div>
  <div class="row" style="text-align: center; justify-content: center;">
    <div class="rules">
      <h2>Turnerings regler</h2>
      <p><%= @tournament.rules %></p>
    </div>
  </div>
  <div class="row" style="text-align: center; justify-content: center;">
    <div class="age-group">
      <h2>Ålders grupp</h2>
      <p><%= @tournament.age_group %> år gamla</p>
    </div>
  </div>
  <div class="row" style="text-align: center; justify-content: center;">
    <div class="skill-level">
      <h2>Prestations nivå</h2>
      <p>Det här är en <%= @tournament.skill_level %> turnering</p>
    </div>
  </div>
  <% if @tournament_winner.present? %>
    <div class="row" style="text-align: center; justify-content: center;">
      <h2>VINNARE!</h2>
    </div>
    <div class="row" style="text-align: center; justify-content: center;">
      <div class="col-10">
        <div class="container-profile w-100">
          <h1 style="color: yellow;"><%= @tournament_winner.club.name %></h1>
          <%= cl_image_tag @tournament_winner.club.photo.key, class:"profile-img-club", alt:"Klubb logga" %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row" style="justify-content: center;">
    <%= link_to "Gruppspelet", tournament_tournament_groups_path(@tournament, @tournament_groups), class:"button-wb" %>
    <% if @tournament.tournament_knockouts.size > 0 %>
      <%= link_to "Slutspelet", tournament_tournament_knockouts_path(@tournament, @tournament.tournament_knockouts), class:"button-wb" %>
    <% end %>
  </div>
  <div class="row" style="justify-content: center;">
    <div class="participating-teams">
      <h2>Deltagande lag</h2>
    </div>
  </div>
  <div class="row" style="justify-content: center;">
    <% @tournament.teams.each do |club| %>
      <div class="col-10">
        <%= link_to club_path(club), class: "d-block" do %>
          <div class="container-profile w-100">
            <% if club.photo.attached? %>
              <%= cl_image_tag club.photo.key, class:"profile-img-club", alt:"Klubb logga" %>
            <% else %>
              <%= image_tag "footballpitch.jpg", class:"profile-img-club", alt:"Klubb logga" %>
            <% end %>
            <div class="content-profile-club">
              <div class="sub-content">
                <h1><%= club.name %></h1>
                <p><strong>Kapten: </strong> <%= club.user.first_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>


  <% if !@existing_request_from_club || !current_user == @tournament.creator.user %>
    <div class="row" style="justify-content: center;">
      <div class="mt-5 mb-3">
        <%= link_to "Join request", tournament_tournament_requests_path(@tournament), class:"button-wb", method: :post %>
      </div>
    </div>
  <% end %>
</div>

<div class="mt-3">
  <% if @pending_tournament_requests.present? && current_user == @tournament.creator.user %>
    <div class="header-card-club">
      <h2>Turnerings förfrågningar</h2>
    </div>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-10 offset-1">
      <% if current_user == @tournament.creator.user %>
        <% @pending_tournament_requests.each do |request| %>
          <div class="club-request-card">
            <div class="d-flex justify-content-center">
              <h5><%= request.club.name %></h5>
            </div>
              <div class="d-flex justify-content-center">
                <%= link_to tournament_request_path(request.id, choice: "accepted"),class:"button-accept badge badge-success d-flex justify-content-center align-items-center", method: :patch do %>
                  <i class="fas fa-check mt-1"></i>
                <% end %>
                <%= link_to tournament_request_path(request.id, choice: "declined"),class:"button-decline badge badge-secondary d-flex justify-content-center align-items-center", method: :patch do %>
                  <i class="fas fa-times mt-1"></i>
                <% end %>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>